### PR TITLE
adding include-once attribute for preventing re-inclusion of unique tags

### PR DESCRIPTION
**Pull request by jbohren**
This PR makes it so adding `include-once="true"` to the root element of a xacro file will prevent that file from being included multiple times.

### CODE REVIEW

**Comment by jbohren** [comment]
Bump.

**Comment by mikepurvis** [comment]
I can picture this being useful for baking up a URDF with a lot of optional components having dependencies. Eg, a base platform that has a mast with several optional peripherals on the mast—including any of those peripherals brings in the mast, but if you want more than one of them, you still only want one instance of the mast. Is this an intended use-case, or are there others you have in mind?

Multiple include is normally a problem because of issues with redefinition, but xacro doesn't mind you redefining a macro.

**Comment by wjwwood** [comment]
Can you rebase this pull request?

**Comment by jbohren** [comment]
> Can you rebase this pull request?

Yeah, I will.

**Comment by wjwwood** [comment]
@jbohren thanks, I guess you are going to open a new pull request then instead of updating this one?

**Comment by jbohren** [comment]
> @jbohren thanks, I guess you are going to open a new pull request then instead of updating this one?

I'll update this one, but I'll leave it closed until it's ready for review again.

**Comment by wjwwood** [comment]
Ok.

**Pull request closed without merging**
