### PR TITLE
Merge changes from kinetic-devel to lunar-devel branch

### PR DESCRIPTION
**Pull request by kartikmohta**
The fixes would be good to have in lunar as well.

### CODE REVIEW

**Comment by rhaschke** [comment]
@codebot Of course we should have those fixes in Lunar as well.
@kartikmohta However, instead of merging, I would suggest some cherry-picks. Merging will also merge version-number changes. Could you, @kartikmohta, please change your PR to use cherry-picks instead?

**Comment by kartikmohta** [comment]
@rhaschke Looking at the file diffs, it doesn't look like there are any version changes. I think a squash and merge would be fine since the diff is small.
BTW, is there any specific need to keep kinetic and lunar as different branches?

**Comment by rhaschke** [comment]
You are right. Merging will not affect any version numbers in package.xml. So, I don't mind to merge as well. But, it's up to @codebot to decide about the merging/rebasing strategy ;-)
Regarding the different branches: Yes, we need different branches as kinetic and lunar have different version numbers. (However, the merging commit doesn't change them).

**Comment by rhaschke** [comment]
I decided to go for cherry picks.

**Pull request closed without merging**
