### PR TITLE
Ported to ROS2 Dashing

### PR DESCRIPTION
**Pull request by kazuki0824**
Same as the title. This PR is based on @vandanamandlik 's #203. Thanks very much.

### CODE REVIEW

**Comment by rhaschke** [comment]
@kazuki0824, could you please describe in which respect this is different to #203?

**Comment by kazuki0824** [comment]
@rhaschke Completely the same for now. This is currently still in progress and set as draft. Further changes are yet to be pushed.

**Comment by rhaschke** [comment]
So, I guess this is simply a rebase of #203 to the latest master so far?

**Comment by kazuki0824** [comment]
@rhaschke Yes, it is.

**Comment by allenh1** [comment]
@kazuki0824 What's the status of this PR? Do you need help with anything?

**Comment by ross-desmond** [comment]
@kazuki0824 It seems like there is some unfinished work with `_find` in substitution_args.py, do you need help switching the find statements to use `ament_index_python.packages`? It does not seem `_get_rospack()` is completely transferable to ROS2 and may require some refactoring.

Please let me know!

**Comment by jacobperron** [comment]
FWIW, I briefly messed around to get find substitution working using ament_index_python: https://github.com/jacobperron/xacro/commit/837e862979616c655d60b57ec24e80d668b00d2b

**Comment by kazuki0824** [comment]
@jacobperron LGTM. Currently this PR is completely the same as #203, and I have an idea that if your workaround is merged with #203, that will become a huge contribution to xacro porting.
So I’d like to this

**Comment by kazuki0824** [comment]
@jacobperron I looked through the commit(https://github.com/jacobperron/xacro/commit/837e862979616c655d60b57ec24e80d668b00d2b). Your substitution_args.py looks great to me. I would like you to send PR to my project. Thank you.

**Comment by jacobperron** [comment]
@kazuki0824 See https://github.com/kazuki0824/xacro/pull/1

**Comment by AAlon** [comment]
@kazuki0824 Can we get that merged in?

**Comment by gonzodepedro** [comment]
Changes on #211

**Pull request closed without merging**
