### PR TITLE
xacro conditional blocks

### PR DESCRIPTION
**Pull request by piyushk**
resubmitting pull request https://github.com/ros/xacro/pull/7 to be merged into hydro-devel

---

This patch allows adding conditionals to xacro with the following syntax. This is useful in the case of configurable robots or loading different gazebo plugins.

```
<xacro:if value="<expression/substitution_arg>">
  <... some xml code here ...>
</xacro:if>
<xacro:unless value="<expression/substitution_arg>">
  <... some xml code here ...>
</xacro:unless>
```

The expression needs to evaluate to "0", "true", "1" or "false", otherwise an error will be thrown. Additionally, the conditional has no effect on macro or property definitions, and is only used while constructing the final xml.

The pull request also includes a minor bug fix. https://github.com/piyushk/xacro/commit/5c0cbd7e939bf8dc782d2914003d7ffd3f25788f

### CODE REVIEW

**Comment by jonbinney** [comment]
Thanks for implementing this piyush!

**Comment by davetcoleman** [comment]
I'm excited about this feature - it is a much needed one that we have actually been talking about with regards to Gazebo URDF models. Thanks!

**Comment by piyushk** [comment]
No problem. I have been used a very nasty wrapper around xacro that uses
sed to get this functionality. I should have implemented this in the first
place.

**Comment by davetcoleman** [comment]
Documented http://ros.org/wiki/xacro#Conditional_Blocks

**Comment by jbohren** [comment]
Sweet.

**Pull request merged**
